JournalNOEP_UI/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JournalNOEP_UI.Controllers
{
    [Authorize]
    public class InfoController : Controller
    {
        private readonly IRepository _repository;

        public InfoController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var model = _repository.DataInfo.OrderBy(x => x.InfoPageNum);
            return View(model);
        }
        public IActionResult PartialEditInfo(Guid? id)
        {
            if (id != Guid.Empty)
            {
                var model = _repository.DataInfo.FirstOrDefault(x => x.Id == id);
                return PartialView(model);
            }
            return PartialView();
        }
        public IActionResult EditInfo(DataInfo dataInfo)
        {
            if (dataInfo.Id != Guid.Empty)
            {
                _repository.Update(dataInfo);
            }
            else
            {
                dataInfo.Id = Guid.NewGuid();
                _repository.Insert(dataInfo);
            }
            return RedirectToAction("Index");
        }
        public IActionResult PartialRemoveInfo(Guid id)
        {
                var model = _repository.DataInfo.FirstOrDefault(x => x.Id == id);
                return PartialView(model);
        }
        public IActionResult RemoveInfo(DataInfo dataInfo)
        {
            var datainf = _repository.DataInfo.FirstOrDefault(x => x.Id == dataInfo.Id);
            _repository.Delete(datainf);
            return RedirectToAction("Index");
        }
    }
}

JournalNOEP_UI/Controllers/JournalController.cs
using JournalNOEP_DOMAIN;
using JournalNOEP_UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace JournalNOEP_UI.Controllers
{
    [Authorize]
    public class JournalController : Controller
    {
        private readonly IRepository _repository;
        IHostingEnvironment _appEnvironment;


        public JournalController(IHostingEnvironment appEnvironment, IRepository repository, IHostingEnvironment environment)
        {
            _appEnvironment = appEnvironment;
            _repository = repository;
        }
        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование года]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult Index(Guid? idedition)
        {
            ViewBag.idedition = idedition ?? null;
            DataViewModel dataViewModel = new DataViewModel()
            {
                DataYearList = _repository.DataYear.Include(x=>x.DataEdition).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult PartialEditYear(Guid? Id)
        {
            Guid id = Id ?? Guid.Empty;
            DataYear dataYear = _repository.DataYear.FirstOrDefault(x => x.Id == id);
            return View(dataYear);
        }
        public void EditYear(DataYear dataYear)
        {
            if (dataYear.Id == Guid.Empty)
            {
                dataYear.Id = Guid.NewGuid();
                _repository.Insert(dataYear);
                DataEdition dataEdition = new DataEdition()
                {
                    Id = Guid.NewGuid(),
                    IdYear = dataYear.Id,
                    Edition = 1
                };
                _repository.Insert(dataEdition);
            }
            else
            {
                _repository.Update(dataYear);
            }
            RedirectToAction("Index");
        }

        public IActionResult PartialRemoveYear(Guid Id)
        {
            DataYear dataYear = _repository.DataYear.FirstOrDefault(x => x.Id == Id);
            return View(dataYear);
        }

        [HttpPost]
        public IActionResult RemoveYear(DataYear dataYear)
        {
            DeleteYear(dataYear);
            return RedirectToAction("Index");
        }
        #endregion

        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование выпуска]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult PartialEditEdition(Guid? IdYear, Guid? IdEdition)
        {
            Guid idyear = IdYear ?? Guid.Empty;
            Guid idedition = IdEdition ?? Guid.Empty;
            DataEdition model;
            if (idyear != Guid.Empty)
            {
                var i = _repository.DataEdition.Where(x => x.IdYear == idyear).Max(x => x.Edition);
                model = new DataEdition()
                {
                    IdYear = idyear,
                    Edition = i + 1
                };
            }
            else
            {
                model = _repository.DataEdition.FirstOrDefault(x => x.Id == idedition);
            }

            return View(model);
        }
        [HttpPost]

        public IActionResult EditEdition(DataEdition dataEdition)
        {
            if (dataEdition.Id == Guid.Empty)
            {
                dataEdition.Id = Guid.NewGuid();
                _repository.Insert(dataEdition);
                return RedirectToAction("Index");
            }
            else
            {
                _repository.Update(dataEdition);
                return RedirectToAction("Index", new { idedition = dataEdition.Id });
            }
        }
        public IActionResult PartialRemoveEdition(Guid IdEdition)
        {
            
              var  model = _repository.DataEdition.FirstOrDefault(x => x.Id == IdEdition);
            
            return View(model);
        }
        [HttpPost]
        public IActionResult RemoveEdition(DataEdition dataEdition)
        {
            DeleteEdition(dataEdition);
            return RedirectToAction("Index");
        }
        public IActionResult PartialEditEditionFile(Guid Id)
        {
            var model = _repository.DataEdition.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialEditEditionFile", model);
        }
        public async Task<IActionResult> EditEditionFile(DataEdition dedition, IFormFile EditionFileNew)
        {
            var _edition = _repository.DataEdition.Include(z=>z.IdYearNavigation).FirstOrDefault(x => x.Id == dedition.Id);
            int AdditionalEdition = _edition.AdditionalEdition ?? 0;
            // путь к папке Files
            string fileName = _edition.IdYearNavigation.Year + "_" + _edition.Edition + "_" + AdditionalEdition + Path.GetExtension(EditionFileNew.FileName);
            string path = Path.Combine("/Files", "EditionFiles", fileName);
            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await EditionFileNew.CopyToAsync(fileStream);
            }
            _edition.EdFile = fileName;
            _repository.Update(_edition);
            return RedirectToAction("Index", new { idedition = _edition.Id });
        }
        public IActionResult PartialRemoveEditionFile(Guid Id)
        {
            var model = _repository.DataEdition.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialRemoveEditionFile", model);
        }
        public IActionResult RemoveEditionFile(DataEdition dedition)
        {
            var _edition = _repository.DataEdition.FirstOrDefault(x => x.Id == dedition.Id);
            _edition.EdFile = null;
            _repository.Update(_edition);
            return RedirectToAction("Index", new { idedition = dedition.Id });
        }

        #endregion

        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование статьи]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult Edition(Guid? idedition)
        {
            var model = _repository.Articles.Include(z => z.Edition).ThenInclude(c => c.IdYearNavigation).Where(x => x.EditionId == idedition).Include(a => a.DataArticleAuthors).ThenInclude(b => b.Author).OrderBy(x => x.ArtPos);
           // var model = _repository.Articles.Include(z => z.Edition).ThenInclude(c => c.IdYearNavigation).Where(x => x.EditionId == idedition).Include(a => a.DataArticleAuthors).ThenInclude(b => b.Author).OrderBy(x => x.ArtPos);
            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == idedition);

            ViewBag.EditionNumber = edition.Edition;
            ViewBag.IdEdition = idedition;
            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;
            ViewBag.DateLastArticle = edition.DateLastArticle;


            return PartialView("Edition/Index", model);
        }
        public IActionResult PartialEditArticleFile(Guid Id)
        {
            var model = _repository.Articles.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialEditArticleFile", model);
        }
        [HttpPost]
        public async Task<IActionResult> EditArticleFile(Articles articless, IFormFile ArtFileNew)
        {

            var articles = _repository.Articles.FirstOrDefault(x => x.Id == articless.Id);
            // путь к папке Files
            string fileName = Guid.NewGuid() + Path.GetExtension(ArtFileNew.FileName);
            string path = Path.Combine("/Files", "ArticleFiles", fileName);
            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await ArtFileNew.CopyToAsync(fileStream);
            }
            articles.ArtFile = fileName;
            _repository.Update(articles);
            return RedirectToAction("Index", new { idedition = articles.EditionId });
        }
        public IActionResult PartialEditArticleFileXml(Guid Id)
        {
            var model = _repository.Articles.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialEditArticleFileXml", model);
        }
        [HttpPost]
        public async Task<IActionResult> EditArticleFileXml(Articles articless, IFormFile ArtFileNew)
        {

            var articles = _repository.Articles.FirstOrDefault(x => x.Id == articless.Id);
            // путь к папке Files
            string fileName = Guid.NewGuid() + Path.GetExtension(ArtFileNew.FileName);
            string path = Path.Combine("/Files", "XmlFiles", fileName);
            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await ArtFileNew.CopyToAsync(fileStream);
            }
            articles.ArtFileXml = fileName;
            _repository.Update(articles);
            return RedirectToAction("Index", new { idedition = articles.EditionId });
        }
        public IActionResult PartialEditArticle(Guid? Id, Guid IdEdition)
        {
            Guid id = Id ?? Guid.Empty;
            var model = _repository.Articles.Include(z => z.DataArticleAuthors).ThenInclude(w => w.Author).FirstOrDefault(x => x.Id == id);
            List<SprJoiurnalAuthors> allAuth = _repository.SprJoiurnalAuthors.OrderBy(x => x.AuthFio).ToList();
            if (model != null)
            {
                List<DataArticleAuthors> artAuthList = model.DataArticleAuthors.ToList();
                List<SprJoiurnalAuthors> artAuth = new List<SprJoiurnalAuthors>();
                foreach (var item in artAuthList)
                {

JournalNOEP_UI/Controllers/ReferenceController.cs
using JournalNOEP_DOMAIN;
using JournalNOEP_UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace JournalNOEP_UI.Controllers
{
    [Authorize]
    public class ReferenceController : Controller
    {
        private readonly IRepository _repository;

        public ReferenceController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }
        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Авторы]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult Authors()
        {
            ReferenceViewModel model = new ReferenceViewModel()
            {
                SprJoiurnalAuthorsList = _repository.SprJoiurnalAuthors
            };
            return View("Authors/Index", model);
        }
        public IActionResult PartialEditAuthor(Guid? idauth)
        {
            Guid id = idauth ?? Guid.Empty;
            SprJoiurnalAuthors model = _repository.SprJoiurnalAuthors.FirstOrDefault(x => x.Id == id);
            return PartialView("Authors/PartialEditAuthor", model);
        }
        [HttpPost]
        public IActionResult EditAuthor(SprJoiurnalAuthors joiurnalAuthors)
        {
            if (joiurnalAuthors.Id == Guid.Empty)
            {
                joiurnalAuthors.Id = Guid.NewGuid();
                _repository.Insert(joiurnalAuthors);
            }
            else
            {
                _repository.Update(joiurnalAuthors);
            }
            return RedirectToAction("Authors");
        }
        public IActionResult PartialRemoveAuthor(Guid idauth)
        {
            Guid id = idauth;
            SprJoiurnalAuthors model = _repository.SprJoiurnalAuthors.FirstOrDefault(x => x.Id == id);
            return PartialView("Authors/PartialRemoveAuthor", model);

        }
        [HttpPost]
        public IActionResult RemoveAuthor(SprJoiurnalAuthors joiurnalAuthors)
        {
            SprJoiurnalAuthors sprJoiurnalAuthors = _repository.SprJoiurnalAuthors.FirstOrDefault(x => x.Id == joiurnalAuthors.Id);
            _repository.Delete(sprJoiurnalAuthors);
            return RedirectToAction("Authors");
        }
        #endregion
    }
}
  

JournalNOEP_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Администратор журнала</title>
    <!-- Vendor css -->
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/Ionicons/css/ionicons.css" rel="stylesheet">
    <link href="~/lib/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
    <link href="~/lib/select2/css/select2.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/spectrum/spectrum.css" rel="stylesheet">
    <!-- Shamcey CSS -->
    <link href="~/css/shamcey.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <style>
        .was-validated .custom-file-input:valid ~ .custom-file-control, .custom-file-input.is-valid ~ .custom-file-control, input.custom-file-input.parsley-success ~ .custom-file-control,
        textarea.custom-file-input.parsley-success ~ .custom-file-control {
            border-color: #23BF08;
        }

            .was-validated .custom-file-input:valid ~ .custom-file-control::before, .custom-file-input.is-valid ~ .custom-file-control::before, input.custom-file-input.parsley-success ~ .custom-file-control::before,
            textarea.custom-file-input.parsley-success ~ .custom-file-control::before {
                border-color: inherit;
            }

        .was-validated .custom-file-input:valid:focus, .custom-file-input.is-valid:focus, input.custom-file-input.parsley-success:focus,
        textarea.custom-file-input.parsley-success:focus {
            box-shadow: 0 0 0 0.2rem rgba(35, 191, 8, 0.25);
        }

        .custom-file-control {
            position: absolute;
            top: 0;
            right: 0;
            left: 0;
            z-index: 5;
            height: 2.5rem;
            padding: 0.5rem 1rem;
            line-height: 1.5;
            color: #495057;
            pointer-events: none;
            user-select: none;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, 0.15);
            border-radius: 3px;
        }

            .custom-file-control:lang(en):empty::after {
                content: "Choose file...";
            }

            .custom-file-control::before {
                position: absolute;
                top: -1px;
                right: -1px;
                bottom: -1px;
                z-index: 6;
                display: block;
                height: 2.5rem;
                padding: 0.5rem 1rem;
                line-height: 1.5;
                color: #495057;
                background-color: #e9ecef;
                border: 1px solid rgba(0, 0, 0, 0.15);
                border-radius: 0 3px 3px 0;
            }

            .custom-file-control:lang(en)::before {
                content: "Browse";
            }

        .custom-file {
            direction: ltr;
        }

        .custom-file-control, .custom-file-control::before {
            border-radius: 0;
        }

        .custom-file-control-primary::before {
            background-color: #0866C6;
            color: #fff;
        }

        .custom-file-control-inverse::before {
            background-color: #343a40;
            color: #fff;
        }
    </style>
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <div class="sh-pagebody">
        <div class="sh-headpanel">
            <div class="sh-headpanel-left">
                <!-- START: HIDDEN IN MOBILE -->
                <a asp-action="Index" asp-controller="Journal" class="sh-icon-link">
                    <div>
                        <i class="icon ion-ios-book-outline"></i>
                        <span>Журнал</span>
                    </div>
                </a>
                <a asp-action="Authors" asp-controller="Reference" class="sh-icon-link">
                    <div>
                        <i class="icon ion-ios-people-outline"></i>
                        <span>Авторы</span>
                    </div>
                </a>
                @*<a asp-action="Section" asp-controller="Reference" class="sh-icon-link">
                    <div>
                        <i class="icon ion-ios-albums-outline"></i>
                        <span>Разделы</span>
                    </div>
                </a>*@
                <a asp-action="Index" asp-controller="Info" class="sh-icon-link">
                    <div>
                        <i class="icon ion-information"></i>
                        <span>Информация</span>
                    </div>
                </a>
                <!-- END: HIDDEN IN MOBILE -->




            </div><!-- sh-headpanel-left -->
            <!-- sh-headpanel-right -->
            <div class="sh-headpanel-right text-white">
                <partial name="_LoginPartial" />
            </div>
        </div><!-- sh-headpanel -->

            <div class="sh-mainpanel">
                <div id="content">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
            <footer>
                <p class="text-center">
                    &copy; @DateTime.Now.Year   - Администратор журнала
                </p>
            </footer>
        </div>
        <script src="~/lib/popper.js/popper.js"></script>
        <script src="~/lib/bootstrap/bootstrap.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
        <script src="~/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
        <script src="~/lib/moment/moment.js"></script>

        <script src="~/js/shamcey.js"></script>
        @RenderSection("Scripts", required: false)

</body>
</html>