JournalAVSE/Controllers/AuthorsController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IRepository _repository;


        public AuthorsController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            MainViewModel authViewModel = new MainViewModel()
            {
                ArticleList = _repository.Articles
                .Include(x => x.DataArticleAuthors).ThenInclude(x => x.Author)
                .Include(x => x.Edition).ThenInclude(x => x.IdYearNavigation).ToList(),
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum)
            };
            return View(authViewModel);


        }
        public IActionResult Articles(Guid authId)
        {
            MainViewModel model = new MainViewModel()
            {
                DataArticleAuthorsList =  _repository.DataArticleAuthors.Where(x=>x.AuthorId == authId).Include(x=>x.Author).Include(x=>x.Article).ThenInclude(x=>x.Edition).ThenInclude(x=>x.IdYearNavigation).Include(x=>x.Article).ThenInclude(x=>x.DataArticleAuthors).ThenInclude(x=>x.Author),
                SprJoiurnalAuthor = _repository.SprJoiurnalAuthors.FirstOrDefault(x=>x.Id == authId)
            };
            return PartialView("Authors/Index", model);


        }
        
    }
}

JournalAVSE/Controllers/EditionsController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class EditionsController : Controller
    {
        private readonly IRepository _repository;


        public EditionsController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(Guid? idedition)
        {
            ViewBag.idedition = idedition ?? null;
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataYearList = _repository.DataYear.Include(x=>x.DataEdition).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult Articles(Guid? idedition)
        {
            var model = _repository.Articles.Where(x => x.EditionId == idedition)
                .Include(x => x.DataArticleAuthors)
                .ThenInclude(x => x.Author).OrderBy(x => x.ArtPos).ToList();
            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == idedition);
            ViewBag.EditionNumber = edition.Edition;
            ViewBag.DateLastArticle = edition.DateLastArticle;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;
            return PartialView("Edition/Index", model);
        }
        public IActionResult LastArticles()
        {
            try
            {
                int LastYear = _repository.DataYear.Max(x => x.Year);

                var LastEdition = _repository.DataEdition.FirstOrDefault(x => x.IdYear == _repository.DataYear.FirstOrDefault(z => z.Year == LastYear).Id);
                var model = _repository.Articles.Where(x => x.EditionId == LastEdition.Id)
                    .Include(x => x.DataArticleAuthors).ThenInclude(x => x.Author).OrderBy(x => x.ArtPos);
                var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == LastEdition.Id);

                ViewBag.EditionNumber = edition.Edition;

                ViewBag.EditionYear = edition.IdYearNavigation.Year;
                ViewBag.EditionFile = edition.EdFile;


                return PartialView("Edition/Index", model);
            }
            catch
            {
                return PartialView("Edition/Index");
            }
        }
        public IActionResult PartialAnnotationView(Guid? articleId)
        {

            MainViewModel articleViewModel = new MainViewModel()
            {
                Article = _repository.Articles.FirstOrDefault(x => x.Id == articleId),
                DataArticleAuthorsList = _repository.DataArticleAuthors.Where(x => x.ArticleId == articleId).Include(x => x.Author)
        };


            return PartialView("Edition/PartialArticleAnnotation", articleViewModel);
        }
    }
}

JournalAVSE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VURO.UI.Models;
using JournalNOEP_DOMAIN;

namespace VURO.UI.Controllers
{
    public class HomeController : Controller
    {



        private readonly IRepository _repository;

        public HomeController(IRepository repository)
        {
            _repository = repository;
        }


        public async Task<IActionResult> MyAction(string returnUrl, string Lang)
        {
            MainViewModel.Language = Lang;
            return  LocalRedirect(returnUrl);
        }

        public IActionResult Index()
        {
            MainViewModel mainViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum)
            };
            return View(mainViewModel);
        }
        public IActionResult PartialHeader()
        {
            MainViewModel mainViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum)
            };
            return PartialView(mainViewModel);
        }
        public IActionResult Journal(Guid? infoId)
        {
            ViewBag.InfoId = infoId;
            MainViewModel mainViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum)
            };
            return View(mainViewModel);
        }
        public IActionResult PartialInfoPage(Guid? id)
        {
            DataInfo dataInfo = _repository.DataInfo.FirstOrDefault(x => x.Id == id);
            return View(dataInfo);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JournalAVSE/Controllers/MetaDataController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class MetaDataController : Controller
    {
        private readonly IRepository _repository;


        public MetaDataController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(Guid? idedition)
        {
            ViewBag.idedition = idedition ?? null;
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataYearList = _repository.DataYear.Include(x => x.DataEdition).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult Articles(Guid? idedition)
        {

            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == idedition);


            var Article = _repository.Articles.Include(x => x.DataArticleAuthors).ThenInclude(c => c.Author).Where(x => x.EditionId == idedition);





            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;
            return PartialView("Edition/Index", Article);
        }
        public IActionResult LastArticles()
        {
           

            int LastYear = _repository.DataYear.Max(x => x.Year);

            var LastEdition = _repository.DataEdition.FirstOrDefault(x => x.IdYear == _repository.DataYear.FirstOrDefault(z => z.Year == LastYear).Id);




            var Article = _repository.Articles.Include(x => x.DataArticleAuthors).ThenInclude(c => c.Author).Where(x => x.EditionId == LastEdition.Id);




            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == LastEdition.Id);

            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;


            return PartialView("Edition/Index", Article);
            throw new Exception();
        }
    }
}

JournalAVSE/Views/Home/Index.cshtml
@model MainViewModel



<partial name="~/Views/Home/PartialHeader.cshtml" />
<!-- start banner Area -->
<section class="banner-area relative">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row fullscreen d-flex justify-content-center align-items-center">
            <div class="banner-content col-lg-10 col-md-12 justify-content-center mt-150">

                @if (MainViewModel.Language != "EN")
                {
                    <h6 class="text-uppercase">Международный НАУЧНЫЙ электронный ЖУРНАЛ</h6>
                    <h1>

                        АКТУАЛЬНЫЕ ВОПРОСЫ СОВРЕМЕННОЙ ЭКОНОМИКИ
                    </h1>
                    <p class="text-white mx-auto" style="font-size:16px;">
                        Свидетельство о регистрации средства массовой информации Федеральной службой по надзору в сфере, информационных технологий и массовых коммуникаций (Роскомнадзор) <strong>ЭЛ № ФС 77-76994</strong> от 11.10.2019 года
                    </p>
                    <a asp-action="Index" asp-controller="Editions" class="primary-btn squire text-uppercase mt-10">Последний выпуск</a>


                }
                else
                {

                    <h6 class="text-uppercase">Science Magazine</h6>
                    <h1>

                        TOPICAL ISSUES OF THE MODERN ECONOMY

                    </h1>
                    <p class="text-white mx-auto" style="font-size:16px;">
                        Certificate of registration of the mass media by the Federal Service for the Supervision of Information Technologies and Mass Communications (Roskomnadzor) <strong> EL No. FS 77-76994 </strong> of 10/11/2019
                    </p>
                    <a asp-action="Index" asp-controller="Editions" class="primary-btn squire text-uppercase mt-10">Latest issue</a>

                }
                <div class="container" style="margin-top:100px;">
                    <div class="row">
                        <div class="col-6 pt-15">
                            <div>
                                <a href="http://obrazovanie.com.ru/index.php/partnery-olimpiady" target="_blank">
                                    <img src="~/img/conf.jpg" />
                                </a>
                            </div>
                        </div>
                        <div class="col-6"><a href="http://qrcoder.ru" target="_blank"><img src="http://qrcoder.ru/code/?http%3A%2F%2Fwww.xn--80ae9b7b.xn--p1ai%2F&4&0" width="148" height="148" border="0" title="QR код"></a></div>
                    </div>

                </div>


            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
<!-- Start item-category Area -->
<!-- End item-category Area -->
<!-- Start about-video Area -->
@foreach (var item in Model.DataInfoList)
{
    if (item.IsSectionOnMainPage == true)
    {

        <section class="about-video-area section-gap">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12 about-video-left">
                        <h1>
                            @item.InfoNameRu
                        </h1>
                        <label>
                            @Html.Raw(item.InfoTextRu)
                        </label>
                    </div>

                </div>
            </div>
        </section>
    }
}
<!-- End about-video Area -->
<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">

        <div class="col-lg-12">
            <p class="footer-text">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright © НП «ДТИПБ» 2013
                @*<script>document.write(new Date().getFullYear());</script>*@
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>

</footer>
<!-- End footer Area -->

JournalAVSE/Views/Home/Journal.cshtml
@model MainViewModel


<partial name="~/Views/Home/PartialHeader.cshtml" /><!-- #header -->
<!-- start banner Area -->
<section class="banner-area relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">

            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->
<div class="container">
    <div id="infoPageDiv">
        @* <partial name="PartialInfoPage.cshtml" />*@
    </div>
</div>
<script>
    window.onload = function () {
        var infoId = '@ViewBag.InfoId';
        $.ajax(
            {
                type: 'POST',
                url: '@Url.Action("PartialInfoPage", "Home")',
                data: { id: infoId },
                success: function (data) {
                    $('#infoPageDiv').html(data);
                }
            }
        );

    }

    $("[data-info-link]").click(function () {
        var infoId = $(this).data("routeId");
        console.log(infoId)
        @*$.ajax(
            {
                type: 'POST',
                url: '@Url.Action("PartialTableCommentts", "Case")',
                data: { id: infoId },
                success: function (data) {
                    $('#commenttsPillContainer').html(data);
                }
            }
        );*@
    });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

JournalAVSE/Views/Home/PartialHeader.cshtml
@model MainViewModel


    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-4 header-top-left no-padding">
                        <div class="menu-social-icons">

                            <a asp-controller="Home" style="float:left;" asp-action="MyAction" asp-route-Lang="RU" asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)">
                                <div style="width:30px;">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
                                    <circle style="fill:#F0F0F0;" cx="256" cy="256" r="256" />







                                    <path style="fill:#0052B4;" d="M496.077,345.043C506.368,317.31,512,287.314,512,256s-5.632-61.31-15.923-89.043H15.923  C5.633,194.69,0,224.686,0,256s5.633,61.31,15.923,89.043L256,367.304L496.077,345.043z" />







                                    <path style="fill:#D80027;" d="M256,512c110.071,0,203.906-69.472,240.077-166.957H15.923C52.094,442.528,145.929,512,256,512z" />















                                </svg>
                                </div>

                            </a>
                            <a asp-controller="Home" style="float:left;" asp-action="MyAction" asp-route-Lang="EN" asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)">
                                <div style="width:30px;">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                         viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<circle style="fill:#F0F0F0;" cx="256" cy="256" r="256" />















<g>
                                    <path style="fill:#0052B4;" d="M52.92,100.142c-20.109,26.163-35.272,56.318-44.101,89.077h133.178L52.92,100.142z" />















                                    <path style="fill:#0052B4;" d="M503.181,189.219c-8.829-32.758-23.993-62.913-44.101-89.076l-89.075,89.076H503.181z" />















                                    <path style="fill:#0052B4;" d="M8.819,322.784c8.83,32.758,23.993,62.913,44.101,89.075l89.074-89.075L8.819,322.784L8.819,322.784
		z" />















                                    <path style="fill:#0052B4;" d="M411.858,52.921c-26.163-20.109-56.317-35.272-89.076-44.102v133.177L411.858,52.921z" />















                                    <path style="fill:#0052B4;" d="M100.142,459.079c26.163,20.109,56.318,35.272,89.076,44.102V370.005L100.142,459.079z" />















                                    <path style="fill:#0052B4;" d="M189.217,8.819c-32.758,8.83-62.913,23.993-89.075,44.101l89.075,89.075V8.819z" />















                                    <path style="fill:#0052B4;" d="M322.783,503.181c32.758-8.83,62.913-23.993,89.075-44.101l-89.075-89.075V503.181z" />















                                    <path style="fill:#0052B4;" d="M370.005,322.784l89.075,89.076c20.108-26.162,35.272-56.318,44.101-89.076H370.005z" />















</g>
<g>
                                    <path style="fill:#D80027;" d="M509.833,222.609h-220.44h-0.001V2.167C278.461,0.744,267.317,0,256,0	c-11.319,0-22.461,0.744-33.391,2.167v220.44v0.001H2.167C0.744,233.539,0,244.683,0,256c0,11.319,0.744,22.461,2.167,33.391 h220.44h0.001v220.442C233.539,511.256,244.681,512,256,512c11.317,0,22.461-0.743,33.391-2.167v-220.44v-0.001h220.442	C511.256,278.461,512,267.319,512,256C512,244.683,511.256,233.539,509.833,222.609z" />















                                    <path style="fill:#D80027;" d="M322.783,322.784L322.783,322.784L437.019,437.02c5.254-5.252,10.266-10.743,15.048-16.435	l-97.802-97.802h-31.482V322.784z" />















                                    <path style="fill:#D80027;" d="M189.217,322.784h-0.002L74.98,437.019c5.252,5.254,10.743,10.266,16.435,15.048l97.802-97.804	V322.784z" />















                                    <path style="fill:#D80027;" d="M189.217,189.219v-0.002L74.981,74.98c-5.254,5.252-10.266,10.743-15.048,16.435l97.803,97.803	H189.217z" />















                                    <path style="fill:#D80027;" d="M322.783,189.219L322.783,189.219L437.02,74.981c-5.252-5.254-10.743-10.266-16.435-15.047
		l-97.802,97.803V189.219z" />







</svg>
                                </div>

                            </a>


                        </div>

                    </div>
                    <div class="col-lg-6 col-sm-6 col-8 header-top-right no-padding">
                        <p class="btns text-white" style="font-size:18px;">ISSN 2311-4320</p>

                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center  d-flex">
                <div class="col-md-3">
                    <a asp-action="Index" asp-controller="Home"><img src="~/img/logo.png" alt="" title="" /></a>
                    <img src="/img/16.png" class="img-responsive" alt="Image" width="40" height="40">
                </div>
                <div class="col-md-9 text-right" >
                    <nav id="nav-menu-container">
                        <ul class="nav-menu">


                            @foreach (var item in Model.DataInfoList.Where(x => x.InfoPageNum >= 30))
                            {
                                if (item.IsSectionOnMainPage == false)
                                {
                                    @if (MainViewModel.Language != "EN")
                                    {
                                        <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                                    }
                                    else
                                    {
                                        <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                                    }
                                }
                            }


                            @if (MainViewModel.Language != "EN")
                            {
                                <li class="menu-active"><a asp-action="Index" asp-controller="Editions">Журнал</a></li>
                                <li class="menu-active"><a asp-action="Index" asp-controller="Authors">Авторы</a></li>
                                <li class="menu-active"><a asp-action="Index" asp-controller="MetaData">Метаданные</a></li>
                            }
                            else
                            {
                                <li class="menu-active"><a asp-action="Index" asp-controller="Editions">Magazine</a></li>
                                <li class="menu-active"><a asp-action="Index" asp-controller="Authors">Authors</a></li>
                                <li class="menu-active"><a asp-action="Index" asp-controller="MetaData">Metadata</a></li>
                            }
                            @foreach (var item in Model.DataInfoList.Where(x => x.InfoPageNum >= 20 && x.InfoPageNum < 30))
                            {
                                if (item.IsSectionOnMainPage == false)
                                {
                                    @if (MainViewModel.Language != "EN")
                                    {
                                        <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                                    }
                                    else
                                    {
                                        <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                                    }
                                }
                            }
                            <li>
                                <a href="#">Информация журнала</a>
                                <ul>
                                    @foreach (var item in Model.DataInfoList.Where(x => x.InfoPageNum < 20))
                                    {
                                        if (item.IsSectionOnMainPage == false)
                                        {
                                            @if (MainViewModel.Language != "EN")
                                            {
                                                <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                                            }
                                            else
                                            {
                                                <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                                            }
                                        }
                                    }
                                </ul>
                            </li>
                        </ul>
                    </nav><!-- #nav-menu-container -->
                </div>
            </div>
        </div>
        
    </header><!-- #header -->

JournalAVSE/Views/Home/PartialInfoPage.cshtml
@model JournalNOEP_DOMAIN.DataInfo
<br>

@if ( MainViewModel.Language  != "EN")
{
    <h2>@Model.InfoNameRu</h2>
    <br>
    @Html.Raw(Model.InfoTextRu)
}
else
{
    <h2>@Model.InfoNameEn</h2>
    <br>
    @Html.Raw(Model.InfoTextEn)
}